name: 'Devio Activity Readme'
description: 'Add DevIO activity to your GitHub profile.'
author: 'bun913'
inputs:
  AUTHOR_ID:
    required: true
    description: 'developersio author id'
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: "bar-chart-2"
  color: "blue"
