name: "Devio Activity Readme"
description: "Add DevIO activity to your GitHub profile."
author: "bun913"
inputs:
  AUTHOR_ID:
    required: true
    description: "developersio author id"
  GH_TOKEN:
    required: false
    default: ${{ github.token }}
    description: "GitHub Token"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        repository: 'bun913/devio-activity'
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: "npx playwright install --with-deps"
      shell: bash
    - run: "node dist/index.js"
      env:
        INPUT_AUTHOR_ID: ${{ inputs.AUTHOR_ID }}
        INPUT_GH_TOKEN: ${{ inputs.GH_TOKEN }}
      shell: bash

branding:
  icon: "bar-chart-2"
  color: "blue"
