name: "Devio Activity Readme"
description: "Add DevIO activity to your GitHub profile."
author: "bun913"
inputs:
  AUTHOR_ID:
    required: true
    description: "developersio author id"
  GH_TOKEN:
    required: false
    default: ${{ github.token }}
    description: "GitHub Token"
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_AUTHOR_ID: ${{ inputs.AUTHOR_ID }}
    INPUT_GH_TOKEN: ${{ inputs.GH_TOKEN }}

branding:
  icon: "bar-chart-2"
  color: "blue"
